### ISSUE TITLE
Could not deserialize key data.

### ISSUE THREAD

**Issue by ghost** [bohops/paSSH#1]
hello, i got some problem
root@vulns:/opt/work/test/paSSH# cp /root/.ssh/id_rsa id_rsa
root@vulns:/opt/work/test/paSSH# python paSSH.py -k id_rsa -p 22

===================== paSSH [SSH Password Revealer] =====================
[-] Exception: Private key file is encrypted
root@vulns:/opt/work/test/paSSH#

[-] Exception: Could not deserialize key data.

So, i delete something from  id_rsa like:

`Proc-Type: 4,ENCRYPTED
DEK-Info: AES-128-CBC,7F3CD1BD8D1462F8A63D8483389FF68E
`
Try again:
root@vulns:/opt/work/test/paSSH# vi id_rsa
root@vulns:/opt/work/test/paSSH# python paSSH.py -k id_rsa -p 22

===================== paSSH [SSH Password Revealer] =====================
[-] Exception: Could not deserialize key data.
root@vulns:/opt/work/test/paSSH#

I think your tool is very cool, but i don't know how to use it, can you help me?

**Comment by bohops** [comment]
Apologies for the delayed reply.  This is an issue with the RSA private key or Paramiko dependency. Have you tried running it with the provided sample key (id_rsa_example)?

**Comment by ghost** [comment]
Thank you for your reply.  I used the file id_rsa_example  to run it, 
when I used the metasploit  for testing, everything is right.

root@vulns:/opt/work/test/paSSH# python paSSH.py -k id_rsa_example -p 22

===================== paSSH [SSH Password Revealer] =====================
[*] Connection Attempt: user= root | passwd= admin@123
[*] Connection Attempt: user= root | passwd= 123456
[*] Connection Attempt: user= root | passwd= 12345678
[*] Connection Attempt: user= root | passwd= 123456789
[*] Connection Attempt: user= root | passwd= 88888888
[*] Connection Attempt: user= root | passwd= 1234567890
[*] Connection Attempt: user= root | passwd= 111111
[*] Connection Attempt: user= root | passwd= 1

But when using the SSH command, it is wrong like:

![image](https://user-images.githubusercontent.com/21474470/48348914-abc7b700-e6bd-11e8-9652-9b74d4194289.png)

**Comment by bohops** [comment]
Ah, it appears that you have a different SSH key association with one that is in your known_hosts file.  Remove the entry then try it again.  I may need to account for this in the code/description.

**Comment by ghost** [comment]
i got it , Thanks...
